### ISSUE TITLE
SCCS package 

### ISSUE THREAD

**Issue by johntaz** [opensafely/r-docker#7]
SCCS: The Self-Controlled Case Series Method

Details:
- package: sccs
- imports: survival, splines, dummies, corpcor, fda, R.methodsS3, gnm
- More details available [here](https://cran.r-project.org/web/packages/SCCS/index.html)

Rationale:
This package implements the basic self-controlled case series method as well as important extensions (such as handling the issue of event-dependent observation periods). This design will be used for the post-covid work and will potentially be useful for the vaccine studies too. 

@annaschultze @wjchulme @esnightingale

**Comment by sebbacon** [comment]
It would be interesting to have a discussion about how we might wrap this up as a standalone action so that non-R users could also benefit.  A discussion for @wjchulme @alexwalkercebm and me (decision to include this doesn't depend on that discussion happening though!) - @alexwalkercebm want to arrange a time slot to talk about it?

**Comment by wjchulme** [comment]
See no reason not to add `SCCS` package.

Keen to discuss standalone actions more generally. My thinking is essentially:

* study definitions are used to define and extract the the minimum necessary dataset for the desired analysis
* given that minimum necessary dataset, we want researchers to retain as much scripting/analytical freedom as possible
* occassionally these two desiderata clash (eg case-control matching, or flowcharts, where you need to extract _more_ patients than are used in the final analysis). We should consider implementing standalone methods for these scenarios.
* we may also want to provide methods for computationally intensive analyses if absolutely necessary, though I think as a rule it's the responsibility of the researcher (not opensafely) to explore how to write code optimally in the first instance. For example, there are lots of R packages that will compile and run C++ directly for speed gains when working with big datasets.

Taking those as general principles for whether or not to provide standalone methods, I'm not convinced that providing a method for SCCS analyses for non-R users is a good use of resource. Especially given it's easy to mix languages within a single analysis. 

Essentially, we should be prioritising helping people overcome the constraints that opensafely necessarily imposes for privacy, security, transparency, etc. Not bridging gaps in users' R knowledge, or gaps in Stata, or whatever it might be. 

Though I may have completely missed the point of your suggestion, @sebbacon

**Comment by johntaz** [comment]
Very interesting discussion @sebbacon @wjchulme ! 

As an example, my planned workflow is to perform data management in Stata/Python and then read a .csv in the correct format to run a specific analysis using this package in R. 

When implementing these standalone methods for the first time, perhaps it would be useful for the analyst to briefly document how it was applied - e.g. required data structure, etc (although this is often in the R documentation). 

@bloodearnest please could you add this to the list of support packages?

**Comment by sebbacon** [comment]
> Essentially, we should be prioritising helping people overcome the constraints that opensafely necessarily imposes for privacy, security, transparency, etc. Not bridging gaps in users' R knowledge, or gaps in Stata, or whatever it might be.

I disagree. Your first point absolutely should be our top priority, but opensafely is also a extraordinary opportunity for us to make best practice easier (for example, keeping all your code in version control; code reviews; reproducibility).

One of these areas is providing quality-assured implementations of common methods.  If there is no case control library available in Stata, then a Stata researcher will have to write their own implementation. It is far preferable for them to use robust, performant, and well-tested implementation that is supported by the opensafely ecosystem.  

There is a virtuous circle here, because if the platform offers, say, a huge performance boost over someone's existing status quo, then they might just use the platform because of that. Then they're suddenly doing things more safely.

Bear in mind this is *already* what we're doing with study definitions: your argument also applies to SQL ("why make people use study definitions when they could just write raw SQL?" answer: because getting the SQL right is hard; so they only have to write it once per backend; because not everyone knows SQL; and more)

To be clear I'm not proposing forcing anyone to use our provided library of implementations. Just that we provide it.

I may misunderstand what SCCS actually *is* so perhaps it's a very bad example!

**Comment by alexwalkercebm** [comment]
I think for commonly used things it could be helpful, but I think it's mostly data management type things rather than stats-y things. Most stats-y things are already an installable library in R and Stata, so I'm not sure how much value adding a distinct OS action would give.

@sebbacon SCCS is Self Controlled Case Series: A type of analysis where patients are used as their own control - the rate of events in an "exposed" time period is compared to the rate before and/or after. This helps to eliminate biases that occur between persons in observational analyses.

This SCCS example is also perhaps a bit niche as an example of something that would be widely used - at least partly because it's possible to do in Stata, it's just that this R package has a neat implementation to avoid a methodological pitfall. (described here http://oro.open.ac.uk/28783/ @johntaz understands this better than I).

Good to have a discussion about this more generally though.

**Comment by wjchulme** [comment]
I basically agree with Alex here. SCCS is a statistical method which, like other methods, is implemented in software that can be run inside opensafely, given the right dataset. There's no more reason to wrap up that as a standalone action than wrap up logistic regression or any other method.

Other reasons we do it with study definitions include

* we don't want people to submit arbitrarily complex SQL to the OS database
* we want to ensure people are extracting only the data they need
* it's our chosen entry point for creating dummy data for the analysis-ready datasets

These are security/data-management issues which typically don't feature when implementing analytical methods, assuming you have the right dataset already.

You're right that we use study definitions because getting analysis-ready datasets from primary care data is hard, and we provide standarised methods to make that easy. This avoids unreadable single project data wrangling spaghetti code, of the sort that I might write if I didn't have the use of a study definition. And yes, unreadable single project code is also an issue for the analysis part of a project. 

But I think we're likely to lose more in analytical flexibility than you gain in computational efficiency and readability if we abstract-away lots of methods via an easy-to-use API. Obviously we could offer both, but I just don't think it would be worth it in most cases, because users will prefer to write analysis code in the way they know how -- in an R or Stata IDE. The fact that OpenSAFELY enables users to write code for primary care data in this way (not logging in to a laggy TRE, or sitting in a cramped basement booth, or only being able to run at the command line) is hopefully a big part of its appeal.

**Comment by wjchulme** [comment]
(meanwhile, @johntaz just wants SCCS to be installed!)

**Comment by bloodearnest** [comment]
Latest R image should have SCCS installed
